yaml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -121,15 +121,15 @@ jobs:
       - checkout
       - run:
           name: Heroku Deploy
-          command: git push https://git.heroku.com/$HEROKU_APP_NAME.git HEAD:main
+          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:master
       - run:
           name: Smoke Test
           command: |
-          HTTPCODE=curl -s -o /dev/null -w "%{http_code}" https://$HEROKU_APP_NAME.herokuapp.com/
-          if [[ "$HTTPCODE" -ne 200 ]]; then
-            echo "heroku app not responding, failing deploy" \
-            exit 1; \
-          fi
+            if [[ "$HTTPCODE" -ne 200 ]]; then
+              echo "heroku app not responding, failing deploy" \
+              exit 1 \
+              HTTPCODE=`curl -s -o /dev/null -w "%{http_code}" https://$HEROKU_APP_NAME.herokuapp.com/`
+            fi
 
 workflows:
   version: 2
