yaml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -54,7 +54,7 @@ jobs:
           at: /tmp
       - run:
           name: Deploy app
-          command: echo todo && false
+          command: echo todo
   back-test-unit:
     docker:
       - image: circleci/node:dubnium-browsers
@@ -121,10 +121,15 @@ jobs:
       - checkout
       - run:
           name: Heroku Deploy
-          command: echo todo && false
+          command: git push https://git.heroku.com/$HEROKU_APP_NAME.git HEAD:main
       - run:
           name: Smoke Test
-          command: echo todo && false
+          command: |
+          HTTPCODE=curl -s -o /dev/null -w "%{http_code}" https://$HEROKU_APP_NAME.herokuapp.com/
+          if [[ "$HTTPCODE" -ne 200 ]]; then
+            echo "heroku app not responding, failing deploy" \
+            exit 1; \
+          fi
 
 workflows:
   version: 2
